import { after, before, beforeEach, test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, getDoc, setDoc, updateDoc } from 'firebase/firestore';

let env;
before(async () => { env = await initializeTestEnvironment({ projectId: 'demo-escala-dashboard', firestore: { host: '127.0.0.1', port: 8087, rules: await readFile(new URL('../firestore.rules', import.meta.url), 'utf8') } }); });
beforeEach(async () => { await env.clearFirestore(); await env.withSecurityRulesDisabled(async (context) => { const db = context.firestore(); await setDoc(doc(db, 'user_links', 'uid-responsavel'), { firebaseUid: 'uid-responsavel', login: 'responsavel.login', active: true, teamIds: ['soc'] }); await setDoc(doc(db, 'user_links', 'uid-outro'), { firebaseUid: 'uid-outro', login: 'outro.login', active: true, teamIds: ['n1'] }); await setDoc(doc(db, 'user_links', 'uid-admin'), { firebaseUid: 'uid-admin', login: 'admin.login', active: true }); await setDoc(doc(db, 'system_admins', 'uid-admin'), { active: true }); await setDoc(doc(db, 'teams', 'soc'), { id: 'soc', teamId: 'soc', active: true, responsibleLogin: 'responsavel.login' }); await setDoc(doc(db, 'teams', 'n1'), { id: 'n1', teamId: 'n1', active: true, responsibleLogin: 'outro.login' }); await setDoc(doc(db, 'schedule_periods', 'soc-period'), { id: 'soc-period', periodId: 'soc-period', teamId: 'soc', active: true, sourceType: 'DASHBOARD' }); await setDoc(doc(db, 'shift_swap_requests', 'swap-soc'), { teamId: 'soc', requesterLogin: 'pessoa.login', status: 'PENDING' }); }); });
after(async () => env.cleanup());

test('nenhuma leitura ou escrita anônima', async () => { const db = env.unauthenticatedContext().firestore(); await assertFails(getDoc(doc(db, 'teams', 'soc'))); await assertFails(setDoc(doc(db, 'schedule_periods', 'x'), { teamId: 'soc' })); });
test('responsável publica somente no próprio time', async () => { const db = env.authenticatedContext('uid-responsavel').firestore(); await assertSucceeds(setDoc(doc(db, 'schedule_assignments', 'a-soc'), { teamId: 'soc', periodId: 'soc-period', source: 'DASHBOARD' })); await assertFails(setDoc(doc(db, 'schedule_assignments', 'a-n1'), { teamId: 'n1', periodId: 'n1-period', source: 'DASHBOARD' })); });
test('responsável não altera teamId', async () => { const db = env.authenticatedContext('uid-responsavel').firestore(); await assertFails(updateDoc(doc(db, 'schedule_periods', 'soc-period'), { teamId: 'n1' })); });
test('escala DEMO é bloqueada', async () => { const db = env.authenticatedContext('uid-responsavel').firestore(); await assertFails(setDoc(doc(db, 'schedule_periods', 'demo'), { teamId: 'soc', sourceType: 'DEMO' })); });
test('system admin administra todos os times', async () => { const db = env.authenticatedContext('uid-admin').firestore(); await assertSucceeds(setDoc(doc(db, 'teams', 'novo'), { id: 'novo', teamId: 'novo', active: true, responsibleLogin: 'responsavel.generico' })); await assertSucceeds(setDoc(doc(db, 'schedule_periods', 'n1-period'), { teamId: 'n1', sourceType: 'DASHBOARD' })); });
test('troca chega ao responsável e outro time não acessa', async () => { const manager = env.authenticatedContext('uid-responsavel').firestore(); const other = env.authenticatedContext('uid-outro').firestore(); await assertSucceeds(getDoc(doc(manager, 'shift_swap_requests', 'swap-soc'))); await assertFails(getDoc(doc(other, 'shift_swap_requests', 'swap-soc'))); await assertSucceeds(updateDoc(doc(manager, 'shift_swap_requests', 'swap-soc'), { status: 'APPROVED', teamId: 'soc' })); });
test('coleções desconhecidas são negadas', async () => { const db = env.authenticatedContext('uid-admin').firestore(); await assertFails(getDoc(doc(db, 'desconhecida', 'x'))); await assertFails(setDoc(doc(db, 'desconhecida', 'x'), { active: true })); });
