import { useState } from 'react';
import type { SheetLayout, Team } from '../types';

const LAYOUTS: SheetLayout[] = ['soc-daily', 'soc-escalistas', 'n1', 'oncall', 'matrix'];
export function TeamDialog({ onCancel, onSave }: { onCancel: () => void; onSave: (team: Team) => void }) {
  const [team, setTeam] = useState<Team>({ id: '', code: '', name: '', responsibleLogin: '', scheduleKind: 'REGULAR', active: true, allowedImportLayouts: [] });
  return <div className="modal-backdrop" role="presentation"><form className="team-dialog" role="dialog" aria-modal="true" aria-label="Cadastrar equipe" onSubmit={(event) => { event.preventDefault(); onSave(team); }}><h2>Cadastrar equipe</h2>
    <label>Código<input required value={team.code} onChange={(event) => setTeam({ ...team, code: event.target.value, id: event.target.value })} /></label><label>Nome<input required value={team.name} onChange={(event) => setTeam({ ...team, name: event.target.value })} /></label><label>Tipo<select value={team.scheduleKind} onChange={(event) => setTeam({ ...team, scheduleKind: event.target.value as Team['scheduleKind'] })}><option value="REGULAR">REGULAR</option><option value="ON_CALL">ON_CALL</option></select></label><label>Responsável pelo time<input required value={team.responsibleLogin} onChange={(event) => setTeam({ ...team, responsibleLogin: event.target.value })} /></label><fieldset><legend>Layouts permitidos</legend>{LAYOUTS.map((layout) => <label key={layout}><input type="checkbox" checked={team.allowedImportLayouts.includes(layout)} onChange={(event) => setTeam({ ...team, allowedImportLayouts: event.target.checked ? [...team.allowedImportLayouts, layout] : team.allowedImportLayouts.filter((item) => item !== layout) })} />{layout}</label>)}</fieldset><label><input type="checkbox" checked={team.active} onChange={(event) => setTeam({ ...team, active: event.target.checked })} />Ativo</label><div className="modal-actions"><button type="button" className="btn" onClick={onCancel}>Cancelar</button><button className="btn btn-primary">Salvar</button></div>
  </form></div>;
}
